lal*/conda/meta.yaml.in.in: run install-python.sh with same script_env as build.sh
- conda-build raises an error for unset vars in script_env for install-*.sh:
    ValueError: env var 'CI_COMMIT_TAG' specified in script_env, but is not set
  This may be a bug as the same error isn't raised for build.sh
- To ensure CI_COMMIT_TAG is passed to all scripts, need to make sure
  CI_COMMIT_TAG is set before calling conda-build, then in scripts only test
  whether CI_COMMIT_TAG is null, not whether it is unsed