Change overzealous strncpy to strcpy
Recent versions of gcc now raise an error when the length passed
to strncpy depends on the length of its argument, because strcpy
is entirely equivalent:

    xtefitstoframe.c: In function 'XLALReadFITSHeader':
    xtefitstoframe.c:795:5: error: 'strncpy' specified bound depends on the length of the source argument [-Werror=stringop-overflow=]
         strncpy(header->filename,c,len);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    xtefitstoframe.c:794:11: note: length computed here
         len = strlen(c) + 1;
           ^~~~~~~~~

I also found and fixed some off-by-one errors:

    xtefitstoframe.c: In function 'XLALEventDataToXTEUINT4TimeSeriesArray':
    xtefitstoframe.c:1954:3: error: 'strncpy' output truncated before terminating nul copying as many bytes from a string as its length [-Werror=stringop-
       strncpy((*ts)->headerdump,fits->header->headerdump,strlen(fits->header->headerdump)*sizeof(CHAR));
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    xtefitstoframe.c: In function 'XLALArrayDataToXTEUINT4TimeSeriesArray':
    xtefitstoframe.c:2141:3: error: 'strncpy' output truncated before terminating nul copying as many bytes from a string as its length [-Werror=stringop-
       strncpy((*ts)->headerdump,fits->header->headerdump,strlen(fits->header->headerdump)*sizeof(CHAR));
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~