Rename unpickling functions to avoid collision with module
The unpickling function for instances of REAL8TimeSeries and
similar classes was called `lal.series`, which collided with a
submodule of the same name. In a multiprocessing application,
this would confuse Python's pickling machinery and cause this
exception:

    multiprocessing.pool.MaybeEncodingError: Error sending result:
    '...'. Reason: 'PicklingError('first item of the tuple returned
    by __reduce__ must be callable')'